### PR TITLE
Fix for not being able to pass arbitrary props to ConnectableComponents

### PR DESCRIPTION
**Pull request by gamedevsam**

### CODE REVIEW

**Comment by raybooysen** [comment]
Hi @gamedevsam thanks for the PR!  Can you maybe explain your requirements for spreading arbitrary props?

For some more context, we're taking the approach that for usage of ConnectableComponent, the mapPublishToProps and mapModelToProps should give you all the information you need for HOCs.  The HOC ideally shouldn't need any props from it's parent, but I'd love to see some reasons for it to exist.

**Comment by gamedevsam** [comment]
Well, it broke my code since I was passing arbitrary props to my view components.

I expected <ConnectedComponent> to be a simple replacement for <SmartComponent>.

Ideally upgrading the library should be a relatively painless process in my opinion.

**Comment by raybooysen** [comment]
Yup, fair enough.  I was way too hasty deleting SmartComponent and it is reinstanted in #17 Let's go with this PR, however, we don't want to commit the dist folder.  This gets published with the NPM package.

**Comment by gamedevsam** [comment]
Thanks for reinstating SmartComponent 👍 

I want benefits of improvements to ESP, but requiring users to refactor working code should be a last resort.

**Pull request closed without merging**
